services:

  db:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27027:27017
    networks:
      - doom
    volumes:
      - mongodbdata:/data/db

  
  api:
    depends_on:
      - db

    container_name: api
    build:
      context: ./fastapi
      dockerfile: Dockerfile_fastapi
    networks:
      - doom
    ports:
      # this works as expected:
      - 8001:8000
    # https://docs.docker.com/compose/how-tos/file-watch/
    # Key is the comment around paths: "All paths are relative to the project directory, apart from ignore file patterns"
    # run with 
    # `$ docker compose up --watch`
    develop:
      watch:
        # this - er - syncs the changes:
        - action: sync
          path: ./
          target: /app
        # but THIS is needed to actually reload those changes: 
        - action: rebuild
          path: ./ 


  svelte:
    container_name: svelte
    build:
      context: ./svelte 
      dockerfile: Dockerfile_svelte
    
    networks:
      - doom

    # map the local port to container port:
    ports:
      - "5173:5173" 
    

volumes:
  mongodbdata:
    # this is crucial if the volume is given a name
    name: mongodbdata

networks:
  doom:
    name: doom