# https://hasura.io/blog/how-to-write-dockerfiles-for-python-web-apps-6d173842ae1d
FROM node:21.6.2-alpine



# set working dir in container:
WORKDIR /svelte

# https://docs.docker.com/reference/dockerfile/#workdir
# copy everything to the container working dir:
COPY . ./

# deploy the node app, based upon the copied config file(s)
RUN npm install --include=dev

# expose the (default) port

# ENV HOST="0.0.0.0"

EXPOSE 5173
# was not HMR-ing, so found this:
# https://github.com/fcrozatier/kit_docker/blob/main/Dockerfile
# CMD ["npm", "rebuild","esbuild","&&", "npm", "run", "dev", "--", "--host"]
# throws error: 
    # npm ERR! code EINVALIDTAGNAME
    # npm ERR! Invalid tag name "&&" of package "&&": Tags may not have any characters that encodeURIComponent encodes.
# CMD npm rebuild esbuild && npm run dev -- --host



# and run the dev server
CMD ["npm","run","dev"]
